# Generated by Django 4.0 on 2024-02-13 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_alter_manage_description_alter_manage_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='manage',
            name='img',
            field=models.ImageField(null=True, upload_to='img'),
        ),
    ]
